//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int IDDanhGia { get; set; }
        public Nullable<int> IDSach { get; set; }
        public Nullable<int> Diem { get; set; }
        public string BinhLuan { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
