//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLI
    {
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
    }
}
